Alert now comes with optionnal explanatory messages
domoticz/domoticz pull request #1356
Opened 2017-03-16 21:48 UTC by DebugBill

SendAlertSensor now needs one more text parameter (only two devices are using this call, so it was easy to update)
If a text is provided, it appears on the GUI next to the numeric level. This allows for the 4 alarm levels to be reported with a explanation/description of the issue
If no text is provided, the behaviour is as before

I've tested with notifications, it did not break anything.
Did not have to modify the GUI code as it already relied on the string database field.

This makes the Text sensor even less usefull as one does not need to use both Alert and Text to report a detailed alarm.

2017-03-17 07:51 UTC, gizmocuz commented
Looks we have a conflict because of a recent pull request merge on ecodevices (i think it was yours...)

2017-03-17 07:52 UTC, gizmocuz commented
Do you have a screenshot of the new sensors usage ?
No need to update all current text sensors ?

2017-03-17 07:56 UTC, DebugBill commented
Here is a screen shot (hopes it goes through GitHub)

It needed an update of all calls to SendAlertSensor…. But there were only 3 throughout the code.
For direct calls to sDecodeRX there is no impact (thanks to my latest change a few minutes ago. It was not true one hour ago)

[cid:image001.png@01D29EFC.4F843FA0]

2017-03-17 08:41 UTC, szczukot requested changes

2017-03-17 08:41 UTC, szczukot commented on hardware/MultiFun.cpp
> +						SendAlertSensor(0, 255, value ? 4 : 1, value ? "Alarm" : "OK", "Alarm");
wrong. Send always "alarm" as text

2017-03-17 08:41 UTC, szczukot commented on hardware/MultiFun.cpp
> +						SendAlertSensor(1, 255, value ? 3 : 1, value ? "Warning" : "OK", "Alarm");
Wrong
Send always "Warning" as text

2017-03-17 08:41 UTC, szczukot commented on hardware/SatelIntegra.cpp
> +	SendAlertSensor(Idx, 255, violation ? 3 : 1, "", "Alert");
I don't want set name for this sensor.
Must be NULL instead "Alert"

2017-03-17 08:42 UTC, gizmocuz commented
Maybe because you are reply by email that the image does not work
Also you copy part of your email into this, which i have to remove

Could you copy/paste it directly in github

Ps. Our automatic build systems have issues, see below (on git)

2017-03-17 09:01 UTC, DebugBill commented
Fixed the merge issue and reverted Multifun and SatelIntegra to original behaviour.

Here is a screenshot

Now waiting for successful build

![alerts](https://cloud.githubusercontent.com/assets/25805255/24036152/a05277ae-0af8-11e7-92c9-494e3ceacc9c.png)

2017-03-17 09:05 UTC, DebugBill commented on hardware/MultiFun.cpp
> +						SendAlertSensor(0, 255, value ? 4 : 1, value ? "Alarm" : "OK", "Alarm");
reverted to original behaviour

2017-03-17 09:06 UTC, DebugBill commented on hardware/MultiFun.cpp
> +						SendAlertSensor(1, 255, value ? 3 : 1, value ? "Warning" : "OK", "Alarm");
reverted to original behaviour

2017-03-17 09:06 UTC, DebugBill commented on hardware/SatelIntegra.cpp
> +	SendAlertSensor(Idx, 255, violation ? 3 : 1, "", "Alert");
reverted to original behaviour

2017-03-17 09:10 UTC, szczukot commented
Idea with additional text is good.
Maybe i will try use it in Satel and MultiFun

2017-03-17 10:04 UTC, DebugBill commented
Please don't merge yet, I'm not happy with the current behaviour but I will not have time to look into it before the week-end

2017-03-17 10:17 UTC, gizmocuz commented
Okey, send me a PM on the forum

2017-03-20 07:16 UTC, DebugBill commented
This version fixes most (I think) of the negative feedback on the forum.
Still some issues with passing text on alerts, but it should not be a major problem.

I did not find any explanation to the crashes reported by some users, I will continue to investigate now that I have many testers.

2017-03-20 09:29 UTC, gizmocuz commented
Please forget the 'negativity' of the feedback... i (most times) consider them as anomalies ;)

2017-03-20 09:31 UTC, merged